name: DVS_RNASEQ
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - bioconductor-deseq2=1.34.0
  - bioconductor-tximport=1.22.0
  - bioconductor-tximportdata=1.22.0
  - gffread=0.12.7
  - r-base=4.1.3
  - r-readr=2.1.2
  - salmon=1.7.0
  - samtools=1.7.1
